import { Track } from '../domains';

export const trackData: Track[] = [
  {
    id: 'kokuritsu',
    prefectureID: 'tokyo',
    name: '国立競技場',
    furigana: 'こくりつ',
    address: '〒160-0013 東京都新宿区霞ヶ丘町１０－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.jpnsport.go.jp/kokuritu/',
    entrance_fee: 200,
  },
  {
    id: 'toneri',
    prefectureID: 'tokyo',
    name: '舎人公園陸上競技場',
    furigana: 'とねり',
    address: '〒121-0837 東京都足立区舎人公園１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.tokyo-park.or.jp/park/format/facilities024.html',
    entrance_fee: 200,
  },
  {
    id: 'akirunodai',
    prefectureID: 'tokyo',
    name: '東京都立秋留台公園陸上競技場',
    furigana: 'あきるのだい',
    address: '〒197-0814 東京都あきる野市二宮６７３－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.tokyo-park.or.jp/announcement/053/detail/38307.html',
    entrance_fee: 200,
  },
  {
    id: 'katsushika',
    prefectureID: 'tokyo',
    name: '葛飾区総合スポーツセンター陸上競技場',
    furigana: 'かつしか',
    address: '〒124-0022 東京都葛飾区奥戸７－１７－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.spo-katsushika.esforta.jp/info_shisetsu_001_c.html',
    entrance_fee: 200,
  },
  {
    id: 'machida',
    prefectureID: 'tokyo',
    name: '町田ＧＩＯＮスタジアム',
    furigana: 'まちだぎおん',
    open_hour: ' 午前9時～午後5時',
    address: '〒195-0063 東京都町田市野津田町２０３５',
    site_url: 'https://www.nozuta-park.com/athletics.html',
    entrance_fee: 200,
  },
  {
    id: 'olynpic',
    prefectureID: 'tokyo',
    name: '駒沢オリンピック公園総合運動場陸上競技場',
    furigana: 'こまざわおりんぴっく',
    address: '〒154-0013 東京都世田谷区駒沢公園１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.tef.or.jp/kopgp/stadium/?no=tab2',
    entrance_fee: 200,
  },
  {
    id: 'riverside',
    prefectureID: 'tokyo',
    name: '台東リバーサイドスポーツセンター陸上競技場',
    furigana: 'だいばりばーさいど',
    address: '〒111-0024 東京都台東区今戸１－１－１０',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.taitocity.net/zaidan/riverside/general/',
    entrance_fee: 200,
  },
  {
    id: 'edogawa',
    prefectureID: 'tokyo',
    name: '江戸川区陸上競技場',
    furigana: 'えどがわ',
    address: '〒134-0087 東京都江戸川区清新町２丁目１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.edogawa-3field.jp/athletics/',
    entrance_fee: 200,
  },
  {
    id: 'yumenoshima',
    prefectureID: 'tokyo',
    name: '江東区夢の島競技場',
    furigana: 'ゆめのしま',
    address: '〒136-0081 東京都江東区夢の島１－１－２',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.di-ksp.jp/facility/yumenoshima_k',
    entrance_fee: 200,
  },
  {
    id: 'kamiyuzuki',
    prefectureID: 'tokyo',
    name: '八王子市上袖木公園陸上競技場',
    furigana: 'はちおうじかみゆずき',
    address: '〒192-0373 東京都八王子市上柚木２丁目４０－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.hachioji.tokyo.jp/shisetsu/104/p012069.html',
    entrance_fee: 200,
  },
  {
    id: 'yoyogi',
    prefectureID: 'tokyo',
    name: '国立代々木競技場',
    furigana: 'こくりつよよぎ',
    open_hour: ' 午前9時～午後5時',
    address: '〒150-0041 東京都渋谷区神南２丁目１－１',
    site_url: 'https://www.jpnsport.go.jp/yoyogi/',
    entrance_fee: 200,
  },
  {
    id: 'hujimori',
    prefectureID: 'tokyo',
    name: '八王子市富士森公園陸上競技場',
    furigana: 'はちおうじふじもり',
    open_hour: ' 午前9時～午後5時',
    address: '〒193-0931 東京都八王子市台町２丁目２',
    site_url:
      'https://www.city.hachioji.tokyo.jp/life/010/002/003/004/p012068.html',
    entrance_fee: 200,
  },
  {
    id: 'ooihuto',
    prefectureID: 'tokyo',
    name: '都立大井ふ頭中央海浜公園スポーツの森陸上競技場',
    furigana: 'かいひんこうえんすぽーつ',
    open_hour: ' 午前9時～午後5時',
    address: '〒140-0003 東京都品川区八潮４丁目１－１９',
    site_url: 'https://seaside-park.jp/park_ooisports/athleticfield/',
    entrance_fee: 200,
  },
  {
    id: 'tama',
    prefectureID: 'tokyo',
    name: '多摩市立陸上競技場',
    furigana: 'たましりつ',
    open_hour: ' 午前9時～午後5時',
    address: '〒206-0024 東京都多摩市諏訪４－９',
    site_url: 'https://www.city.tama.lg.jp/0000002707.html',
    entrance_fee: 200,
  },
  {
    id: 'setagaya',
    prefectureID: 'tokyo',
    name: '世田谷区総合運動場陸上競技場',
    furigana: 'せたがやそうごう',
    open_hour: ' 午前9時～午後5時',
    address: '〒157-0074 東京都世田谷区大蔵４－６－１',
    site_url: 'https://www.se-sports.or.jp/facility/sougou/',
    entrance_fee: 200,
  },
  {
    id: 'musasino',
    prefectureID: 'tokyo',
    name: '武蔵野市立武蔵野陸上競技場',
    furigana: 'むさしの',
    open_hour: ' 午前9時～午後5時',
    address: '〒180-0001 東京都武蔵野市吉祥寺北町５丁目１１－２０',
    site_url: 'https://www.musashino.or.jp/sports/1001550/1001570.html',
    entrance_fee: 200,
  },
  {
    id: 'tachikawa',
    prefectureID: 'tokyo',
    name: '立川公園陸上競技場',
    furigana: 'たちかわ',
    address: '〒190-0022 東京都立川市錦町６丁目２９－６２',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.tachikawa.lg.jp/supotsushinko/shisetsu/sport/002-s.html',
    entrance_fee: 200,
  },
  {
    id: 'higasikane',
    prefectureID: 'chiba',
    name: '東金アリーナ',
    furigana: 'ひがしかねありーな',
    address: '〒283-0063 千葉県東金市堀上１３６１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.togane-bunspo.or.jp/arena/',
    entrance_fee: 200,
  },
  {
    id: 'zaori',
    prefectureID: 'chiba',
    name: 'ゼットエーオリプリスタジアム',
    furigana: 'ぜっとえー',
    address: '市原市岩崎５３６',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.ichihara.chiba.jp/article?articleId=60238265ece4651c88c19639',
    entrance_fee: 200,
  },
  {
    id: 'kasiwanoha',
    prefectureID: 'chiba',
    name: '千葉県立柏の葉公園総合競技場',
    furigana: 'かしわのは',
    address: '〒277-0882 千葉県柏市柏の葉４丁目１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.cue-net.or.jp/kouen/kasiwa/annai/stadium.html',
    entrance_fee: 200,
  },
  {
    id: 'noda',
    prefectureID: 'chiba',
    name: '野田市総合公園陸上競技場',
    furigana: 'のだそうごうこうえん',
    address: '〒278-0043 千葉県野田市清水９５８',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.noda.chiba.jp/shisetsu/kouen/1001068.html',
    entrance_fee: 200,
  },
  {
    id: 'matsuyamasita',
    prefectureID: 'chiba',
    name: '印西市松山下公園陸上競技場',
    furigana: 'まつやました',
    address: '〒270-1367 千葉県印西市浦部２７５',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.inzai.lg.jp/0000001700.html',
    entrance_fee: 200,
  },
  {
    id: 'nakadai',
    prefectureID: 'chiba',
    name: '中台運動公園陸上競技場',
    furigana: 'なかだい',
    address: '〒286-0015 千葉県成田市中台５－２',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.park-narita.jp/shisetsu/shisetsu_ichiran/nakadai/',
    entrance_fee: 200,
  },
  {
    id: 'chbasougou',
    prefectureID: 'chiba',
    name: '千葉県総合スポーツセンター陸上競技場',
    furigana: 'ちばそうごう',
    address: '〒263-0011 千葉県千葉市稲毛区天台町３２３',
    open_hour: ' 午前9時～午後5時',
    site_url: '',
    entrance_fee: 200,
  },
  {
    id: 'hunabasiundou',
    prefectureID: 'chiba',
    name: '船橋市運動公園陸上競技場',
    furigana: 'ふなばしそうごう',
    address: '〒273-0866 千葉県船橋市夏見台６丁目４－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.cue-net.or.jp/kouen/sportscenter/annai/stadium.html',
    entrance_fee: 200,
  },
  {
    id: 'sirai',
    prefectureID: 'chiba',
    name: '白井市陸上競技場',
    furigana: 'しらい',
    address: '〒270-1416 千葉県白井市神々廻1728-1',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://shisetsu.mizuno.jp/m-7628-02',
    entrance_fee: 200,
  },
  {
    id: 'aobanomori',
    prefectureID: 'chiba',
    name: '千葉県青葉の森スポーツプラザ陸上競技場',
    furigana: 'あおばのもり',
    address: '〒260-0852 千葉県千葉市中央区青葉町６５４',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://shiroiundokoen.jp/facility/%E9%99%B8%E4%B8%8A%E7%AB%B6%E6%8A%80%E5%A0%B4/',
    entrance_fee: 200,
  },
  {
    id: 'matsudo',
    prefectureID: 'chiba',
    name: '松戸運動公園陸上競技場',
    furigana: 'まつどうんどう',
    address: '〒271-0064 千葉県松戸市上本郷４４３４',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.sc-chiba.com/shisetsu/aobanomori/',
    entrance_fee: 200,
  },
  {
    id: 'iwana',
    prefectureID: 'chiba',
    name: '岩名運動公園陸上競技場',
    furigana: 'いわな',
    address: '〒285-0004 千葉県佐倉市岩名７５３',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.matsudo.chiba.jp/shisetsu-guide/sports/unndoukouen.html',
    entrance_fee: 200,
  },
  {
    id: 'kamogawa',
    prefectureID: 'chiba',
    name: '鴨川市陸上競技場',
    furigana: 'かもがわ',
    address: '〒296-0014 千葉県鴨川市太尾８６６－１',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'http://www.iwana.shiteikanri-sakura.jp/iwa/annai/iwana/stadium.html',
    entrance_fee: 200,
  },
  {
    id: 'chibasougou',
    prefectureID: 'chiba',
    name: '千葉県総合スポーツセンター第2陸上競技場',
    furigana: 'ちばそうごう',
    address: '〒263-0011 千葉県千葉市稲毛区天台町３２３',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.kamogawa.lg.jp/site/shisetsu/111.html',
    entrance_fee: 200,
  },
  {
    id: 'narihigashi',
    prefectureID: 'chiba',
    name: '成東総合運動公園陸上競技場',
    furigana: 'なりひがしそうごう',
    address: '〒289-1316 千葉県山武市五木田３２４１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.sammu.lg.jp/page/page001386.html',
    entrance_fee: 200,
  },
  {
    id: 'nitta',
    prefectureID: 'gunma',
    name: '太田市新田陸上競技場',
    furigana: 'おおたしにった',
    address: '〒370-0341 群馬県太田市新田金井町３１',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.ota.gunma.jp/020sisetu/02sports/nitta-rikujyo.html',
    entrance_fee: 200,
  },
  {
    id: 'hamakawa',
    prefectureID: 'gunma',
    name: '浜川競技場',
    furigana: 'はまかわ',
    address: '〒370-0081 群馬県高崎市浜川町１４８６',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'http://takasaki-foundation.or.jp/sports/05kyougi/hamagawa-kyougi.html',
    entrance_fee: 200,
  },
  {
    id: 'ootaundou',
    prefectureID: 'gunma',
    name: '太田市運動公園陸上競技場',
    furigana: 'おおたしうんどう',
    address: '〒373-0817 群馬県太田市飯塚町１０５９',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.ota.gunma.jp/020sisetu/02sports/rikujyo.html',
    entrance_fee: 200,
  },
  {
    id: 'miyagisougou',
    prefectureID: 'gunma',
    name: '前橋市宮城総合運動場陸上競技場',
    furigana: 'みやぎそうごう',
    address: '〒371-0244 群馬県前橋市鼻毛石町２２７０－１',
    open_hour: ' 午前9時～午後5時',
    entrance_fee: 200,
    site_url: 'https://www.maebashi-cc.or.jp/tohbutiku/miyagisogo',
  },
  {
    id: 'isesaki',
    prefectureID: 'gunma',
    name: '伊勢崎市華蔵寺公園陸上競技場',
    furigana: 'いせさきしけぞうじ',
    address: '〒372-0002 群馬県伊勢崎市堤西町１２１',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.isesaki.lg.jp/soshiki/kensui/sport/sisetukanri/shisetsu/3078.html',
    entrance_fee: 200,
  },
  {
    id: 'kiryuu',
    prefectureID: 'gunma',
    name: '桐生市陸上競技場',
    furigana: 'きりゅう',
    address: '〒376-0027 群馬県桐生市元宿町１７－３３',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.kiryu.lg.jp/shisetsu/sports/taiiku/1002884.html',
    entrance_fee: 200,
  },
  {
    id: 'kanramachi',
    prefectureID: 'gunma',
    name: '甘楽町陸上競技場',
    furigana: 'かんらまち',
    address: '〒370-2213 群馬県甘楽郡甘楽町大字白倉１３４３',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.town.kanra.lg.jp/kyouiku/taiiku/map/08.html',
    entrance_fee: 200,
  },
  {
    id: 'nissan',
    prefectureID: 'kanagawa',
    name: '日産スタジアム',
    furigana: 'にっさん',
    address: '〒222-0036 神奈川県横浜市港北区小机町３３００',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.nissan-stadium.jp/track/index.php',
    entrance_fee: 200,
  },
  {
    id: 'todoroki',
    prefectureID: 'kanagawa',
    name: '等々力陸上競技場',
    furigana: 'とどろき',
    address: '〒211-0052 神奈川県川崎市中原区等々力１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.kawasaki.jp/nakahara/page/0000088519.html',
    entrance_fee: 200,
  },
  {
    id: 'yamato',
    prefectureID: 'kanagawa',
    name: '大和市大和スポーツセンター競技場',
    furigana: 'やまと',
    address: '〒242-0029 神奈川県大和市上草柳１－１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.yamato-zaidan.or.jp/sportscenter/stadium',
    entrance_fee: 200,
  },
  {
    id: 'atsugi',
    prefectureID: 'kanagawa',
    name: '厚木市荻野運動公園陸上競技場',
    furigana: 'あつぎしおぎの',
    address: '〒243-0202 神奈川県厚木市中荻野１５００',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://ogino-park.jp/stadium.html',
    entrance_fee: 200,
  },
  {
    id: 'lemongas',
    prefectureID: 'kanagawa',
    name: 'レモンガススタジアム平塚',
    furigana: 'れもんがす',
    address: '〒254-0074 神奈川県平塚市大原１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.hiratsuka.kanagawa.jp/koen/page-c_00810.html',
    entrance_fee: 200,
  },
  {
    id: 'mimase',
    prefectureID: 'kanagawa',
    name: '三増公園陸上競技場',
    furigana: 'みませ',
    address: '〒243-0308 神奈川県愛甲郡愛川町三増１８８６',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.town.aikawa.kanagawa.jp/soshiki/kyouikuiinkai/spobun/mimase/1472619596428.html',
    entrance_fee: 200,
  },
  {
    id: 'taikucenter',
    prefectureID: 'kanagawa',
    name: '神奈川県立体育センター陸上競技場',
    furigana: 'たいいくせんたー',
    address: '〒251-0871 神奈川県藤沢市善行７－１－２',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://shisetsu.mizuno.jp/m-7624',
    entrance_fee: 200,
  },
  {
    id: 'ebina',
    prefectureID: 'kanagawa',
    name: '海老名運動公園陸上競技場',
    furigana: 'えびなうんどう',
    address: '〒243-0424 神奈川県海老名市社家４０３２－１',

    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.city.ebina.kanagawa.jp/guide/bunka/sports/1011492/1011517.html',
    entrance_fee: 200,
  },
  {
    id: 'siroyama',
    prefectureID: 'kanagawa',
    name: '城山陸上競技場',
    furigana: 'siroyama',
    address: '〒250-0045 神奈川県小田原市城山２丁目２９－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://odawaraarena.main.jp/odawara_shiroyama.htm',
    entrance_fee: 200,
  },
  {
    id: 'kamio',
    prefectureID: 'saitama',
    name: '上尾運動公園陸上競技場',
    furigana: 'かみおうんどう',
    address: '〒362-0034 埼玉県上尾市愛宕３丁目２８－３０',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.parks.or.jp/saitamasuijo/guide/000/000019.html',
    entrance_fee: 200,
  },
  {
    id: 'komaba',
    prefectureID: 'saitama',
    name: '浦和駒場スタジアム',
    furigana: 'うらわこまば',
    address: '〒330-0051 埼玉県さいたま市浦和区駒場２丁目１－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.urawa-reds.co.jp/game/stadium/komaba.php',
    entrance_fee: 200,
  },
  {
    id: 'higasimatsuyama',
    prefectureID: 'saitama',
    name: '東松山陸上競技場',
    furigana: 'ひがしまつやま',
    address: '〒355-0005 埼玉県東松山市大字松山１４８１',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'http://www.city.higashimatsuyama.lg.jp/shisetsu/shisetsumenu7/1353926964505.html',
    entrance_fee: 200,
  },
  {
    id: 'kumagayabunka',
    prefectureID: 'saitama',
    name: '熊谷スポーツ文化公園陸上競技場',
    furigana: 'くまがやすぽーつ',
    address: '〒360-0004 埼玉県熊谷市大字上川上３００',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.parks.or.jp/kumagaya/guide/001/001816.html',
    entrance_fee: 200,
  },
  {
    id: 'kouzu',
    prefectureID: 'saitama',
    name: '鴻巣市立陸上競技場',
    furigana: 'こうず',
    address: '〒365-0028 埼玉県鴻巣市大字鴻巣６３４－２',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://konosu-sports.com/field_track/',
    entrance_fee: 200,
  },
  {
    id: 'kumagayaundou',
    prefectureID: 'saitama',
    name: '熊谷運動公園陸上競技場',
    furigana: 'くまがやうんどう',
    address: '〒360-0832 埼玉県熊谷市小島１５７－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.saispo.jp/sakura/page-2384/',
    entrance_fee: 200,
  },
  {
    id: 'kawagoeundou',
    prefectureID: 'saitama',
    name: '川越運動公園陸上競技場',
    furigana: 'かわごえうんどう',
    address: '〒350-0848 埼玉県川越市下老袋３８８－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.kfp.or.jp/facilities/sportspark',
    entrance_fee: 200,
  },
  {
    id: 'yoshimi',
    prefectureID: 'saitama',
    name: '吉見町ふれあい広場陸上競技場',
    furigana: 'よしみまち',
    address: '〒355-0164 埼玉県比企郡吉見町小新井１４２',
    open_hour: ' 午前9時～午後5時',
    site_url:
      'https://www.town.yoshimi.saitama.jp/soshiki/shogaigakushuk/4/6/529.html',
    entrance_fee: 200,
  },
  {
    id: 'shirakobato',
    prefectureID: 'saitama',
    name: 'しらこばと運動公園競技場',
    furigana: 'しらこばと',
    address: '〒343-0802 埼玉県越谷市小曽川７２９－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://kouen-kyougijyou.kosi-kanri.com/',
    entrance_fee: 200,
  },
  {
    id: 'aokimachi',
    prefectureID: 'saitama',
    name: '青木町公園総合運動場内陸上競技場',
    furigana: 'あおきまち',
    address: '〒332-0035 埼玉県川口市西青木４丁目８－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://kawaspo.jp/pages/24/',
    entrance_fee: 200,
  },
  {
    id: 'asaka',
    prefectureID: 'saitama',
    name: '朝霞中央公園陸上競技場',
    furigana: 'あさかちゅうおう',
    address: '〒351-0016 埼玉県朝霞市青葉台１丁目９－１',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.asaka.lg.jp/soshiki/41/chuourikujou.html',
    entrance_fee: 200,
  },
  {
    id: 'niiza',
    prefectureID: 'saitama',
    name: '新座市総合運動公園陸上競技場',
    furigana: 'にいざそうごううんどう',
    address: '〒352-0022 埼玉県新座市本多２丁目８－１６',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.niiza.lg.jp/map/sogoundokoen2022.html',
    entrance_fee: 200,
  },
  {
    id: 'sengennzan',
    prefectureID: 'saitama',
    name: '仙元山運動公園陸上競技場',
    furigana: 'せんげんざん',
    address: '〒366-0801 埼玉県深谷市上野台２５６８',
    open_hour: ' 午前9時～午後5時',
    site_url: 'http://city-fukayakousha.com/bigturtle/gra.html',
    entrance_fee: 200,
  },
  {
    id: 'bessho',
    prefectureID: 'saitama',
    name: '別所運動公園競技場',
    furigana: 'べっしょうんどう',
    address: '〒368-0054 埼玉県秩父市別所１６９５',
    open_hour: ' 午前9時～午後5時',
    site_url: 'https://www.city.chichibu.lg.jp/1157.html',
    entrance_fee: 200,
  },
];
